### ISSUE TITLE
To be done for OC 6

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#62]
- [x] Fade in top bar on use
- [x] Jans issues (see mail)
- [x] hide sidebar
- [x] play everywhere (FF, Chrome, IE)
- [x] height playbar (1.5x)
- [x] move down playbar
- [ ] Albumcover (folder.jpg) #76
- [ ] Ampache #60
- [ ] shuffle / repeat (one-way toggles) #77
- [ ] virtual scrolling (http://sergimansilla.com/blog/virtual-scrolling/) #78
- [ ] "scroll" bar anchor to alphabet (Firefox OS music app https://github.com/mozilla-b2g/gaia/tree/master/apps/music) #79
- [x] Handle tracks without artist and/or album (they are inside of the database, but aren't displayed)
- [ ] the play controls should be aligned with the first album cover column of the content. Centered. (bit to the right from the current place)
- [ ] the now playing album cover should be left aligned with the track names of the first album column. (bit to the right from current place)
- [ ] the progress bar is way too far to the right. Should be left aligned with the second album cover column and be on the same height as the artist name so the song name could be longer
- [ ] the currently playing song needs to be highlighted in the content list, and have a pause icon next to it.
- [ ] there needs to be a bit more vertical whitespace between artists in the content area. _not_ more whitespace between the album rows though
- [x] in the content view, each track should have the track number left of it. Use an ordered list `<ol>` for the track list to achieve that automatically. The track numbers should be grey/transparent similar to the »Show all« so that they are not so obtrusive. 
- [ ] On hovering the track, the Play icon should replace the track number, no need for extra space.
- [x] instead of just »Show all …«, the number of songs should be there: »Show all 14 songs …« for instance.

cc @jancborchardt @karlitschek @butonic @Raydiation
